export const TICKERS: { symbol: string; name: string }[] = [
  { symbol: "AAPL", name: "Apple Inc." },
  { symbol: "MSFT", name: "Microsoft Corp." },
  { symbol: "GOOGL", name: "Alphabet Inc. (Class A)" },
  { symbol: "GOOG", name: "Alphabet Inc. (Class C)" },
  { symbol: "AMZN", name: "Amazon.com Inc." },
  { symbol: "NVDA", name: "NVIDIA Corp." },
  { symbol: "META", name: "Meta Platforms Inc." },
  { symbol: "TSLA", name: "Tesla Inc." },
  { symbol: "BRK.B", name: "Berkshire Hathaway (Class B)" },
  { symbol: "BRK.A", name: "Berkshire Hathaway (Class A)" },
  { symbol: "JPM", name: "JPMorgan Chase & Co." },
  { symbol: "V", name: "Visa Inc." },
  { symbol: "JNJ", name: "Johnson & Johnson" },
  { symbol: "WMT", name: "Walmart Inc." },
  { symbol: "MA", name: "Mastercard Inc." },
  { symbol: "PG", name: "Procter & Gamble Co." },
  { symbol: "UNH", name: "UnitedHealth Group Inc." },
  { symbol: "HD", name: "Home Depot Inc." },
  { symbol: "DIS", name: "Walt Disney Co." },
  { symbol: "BAC", name: "Bank of America Corp." },
  { symbol: "XOM", name: "Exxon Mobil Corp." },
  { symbol: "PFE", name: "Pfizer Inc." },
  { symbol: "CSCO", name: "Cisco Systems Inc." },
  { symbol: "ADBE", name: "Adobe Inc." },
  { symbol: "CRM", name: "Salesforce Inc." },
  { symbol: "NFLX", name: "Netflix Inc." },
  { symbol: "AMD", name: "Advanced Micro Devices Inc." },
  { symbol: "INTC", name: "Intel Corp." },
  { symbol: "CMCSA", name: "Comcast Corp." },
  { symbol: "PEP", name: "PepsiCo Inc." },
  { symbol: "KO", name: "Coca-Cola Co." },
  { symbol: "COST", name: "Costco Wholesale Corp." },
  { symbol: "ABT", name: "Abbott Laboratories" },
  { symbol: "TMO", name: "Thermo Fisher Scientific Inc." },
  { symbol: "AVGO", name: "Broadcom Inc." },
  { symbol: "NKE", name: "Nike Inc." },
  { symbol: "MRK", name: "Merck & Co. Inc." },
  { symbol: "LLY", name: "Eli Lilly & Co." },
  { symbol: "ORCL", name: "Oracle Corp." },
  { symbol: "CVX", name: "Chevron Corp." },
  { symbol: "ABBV", name: "AbbVie Inc." },
  { symbol: "ACN", name: "Accenture plc" },
  { symbol: "MCD", name: "McDonald's Corp." },
  { symbol: "QCOM", name: "Qualcomm Inc." },
  { symbol: "TXN", name: "Texas Instruments Inc." },
  { symbol: "GS", name: "Goldman Sachs Group Inc." },
  { symbol: "MS", name: "Morgan Stanley" },
  { symbol: "LOW", name: "Lowe's Companies Inc." },
  { symbol: "UPS", name: "United Parcel Service Inc." },
  { symbol: "SBUX", name: "Starbucks Corp." },
  { symbol: "PYPL", name: "PayPal Holdings Inc." },
  { symbol: "SQ", name: "Block Inc." },
  { symbol: "SHOP", name: "Shopify Inc." },
  { symbol: "SNAP", name: "Snap Inc." },
  { symbol: "UBER", name: "Uber Technologies Inc." },
  { symbol: "LYFT", name: "Lyft Inc." },
  { symbol: "ABNB", name: "Airbnb Inc." },
  { symbol: "COIN", name: "Coinbase Global Inc." },
  { symbol: "HOOD", name: "Robinhood Markets Inc." },
  { symbol: "PLTR", name: "Palantir Technologies Inc." },
  { symbol: "SNOW", name: "Snowflake Inc." },
  { symbol: "NET", name: "Cloudflare Inc." },
  { symbol: "CRWD", name: "CrowdStrike Holdings Inc." },
  { symbol: "DDOG", name: "Datadog Inc." },
  { symbol: "ZS", name: "Zscaler Inc." },
  { symbol: "PANW", name: "Palo Alto Networks Inc." },
  { symbol: "RIVN", name: "Rivian Automotive Inc." },
  { symbol: "LCID", name: "Lucid Group Inc." },
  { symbol: "F", name: "Ford Motor Co." },
  { symbol: "GM", name: "General Motors Co." },
  { symbol: "BA", name: "Boeing Co." },
  { symbol: "CAT", name: "Caterpillar Inc." },
  { symbol: "DE", name: "Deere & Co." },
  { symbol: "RTX", name: "RTX Corp." },
  { symbol: "LMT", name: "Lockheed Martin Corp." },
  { symbol: "GE", name: "GE Aerospace" },
  { symbol: "MMM", name: "3M Co." },
  { symbol: "HON", name: "Honeywell International Inc." },
  { symbol: "AXP", name: "American Express Co." },
  { symbol: "SPGI", name: "S&P Global Inc." },
  { symbol: "BLK", name: "BlackRock Inc." },
  { symbol: "SCHW", name: "Charles Schwab Corp." },
  { symbol: "C", name: "Citigroup Inc." },
  { symbol: "WFC", name: "Wells Fargo & Co." },
  { symbol: "USB", name: "U.S. Bancorp" },
  { symbol: "AIG", name: "American International Group" },
  { symbol: "MET", name: "MetLife Inc." },
  { symbol: "PRU", name: "Prudential Financial Inc." },
  { symbol: "T", name: "AT&T Inc." },
  { symbol: "VZ", name: "Verizon Communications Inc." },
  { symbol: "TMUS", name: "T-Mobile US Inc." },
  { symbol: "CL", name: "Colgate-Palmolive Co." },
  { symbol: "EL", name: "Estee Lauder Companies Inc." },
  { symbol: "PM", name: "Philip Morris International" },
  { symbol: "MO", name: "Altria Group Inc." },
  { symbol: "MDLZ", name: "Mondelez International Inc." },
  { symbol: "GIS", name: "General Mills Inc." },
  { symbol: "K", name: "Kellanova" },
  { symbol: "HSY", name: "Hershey Co." },
  { symbol: "SO", name: "Southern Co." },
  { symbol: "DUK", name: "Duke Energy Corp." },
  { symbol: "NEE", name: "NextEra Energy Inc." },
  { symbol: "D", name: "Dominion Energy Inc." },
  { symbol: "SRE", name: "Sempra" },
  { symbol: "SPY", name: "SPDR S&P 500 ETF Trust" },
  { symbol: "QQQ", name: "Invesco QQQ Trust" },
  { symbol: "IWM", name: "iShares Russell 2000 ETF" },
  { symbol: "DIA", name: "SPDR Dow Jones Industrial ETF" },
  { symbol: "VTI", name: "Vanguard Total Stock Market ETF" },
  { symbol: "VOO", name: "Vanguard S&P 500 ETF" },
  { symbol: "ARKK", name: "ARK Innovation ETF" },
  { symbol: "XLF", name: "Financial Select Sector SPDR" },
  { symbol: "XLE", name: "Energy Select Sector SPDR" },
  { symbol: "XLK", name: "Technology Select Sector SPDR" },
  { symbol: "GLD", name: "SPDR Gold Shares" },
  { symbol: "SLV", name: "iShares Silver Trust" },
  { symbol: "BITO", name: "ProShares Bitcoin Strategy ETF" },
  { symbol: "SOFI", name: "SoFi Technologies Inc." },
  { symbol: "ROKU", name: "Roku Inc." },
  { symbol: "RBLX", name: "Roblox Corp." },
  { symbol: "U", name: "Unity Software Inc." },
  { symbol: "PATH", name: "UiPath Inc." },
  { symbol: "AI", name: "C3.ai Inc." },
  { symbol: "SMCI", name: "Super Micro Computer Inc." },
  { symbol: "ARM", name: "Arm Holdings plc" },
  { symbol: "MRVL", name: "Marvell Technology Inc." },
  { symbol: "MU", name: "Micron Technology Inc." },
  { symbol: "LRCX", name: "Lam Research Corp." },
  { symbol: "KLAC", name: "KLA Corp." },
  { symbol: "AMAT", name: "Applied Materials Inc." },
  { symbol: "TSM", name: "Taiwan Semiconductor (ADR)" },
  { symbol: "ASML", name: "ASML Holding NV (ADR)" },
  { symbol: "BABA", name: "Alibaba Group (ADR)" },
  { symbol: "JD", name: "JD.com Inc. (ADR)" },
  { symbol: "PDD", name: "PDD Holdings Inc. (ADR)" },
  { symbol: "NIO", name: "NIO Inc. (ADR)" },
  { symbol: "LI", name: "Li Auto Inc. (ADR)" },
  { symbol: "XPEV", name: "XPeng Inc. (ADR)" },
  { symbol: "SE", name: "Sea Limited (ADR)" },
  { symbol: "GRAB", name: "Grab Holdings Ltd." },
  { symbol: "MELI", name: "MercadoLibre Inc." },
  { symbol: "NU", name: "Nu Holdings Ltd." },
  { symbol: "SPOT", name: "Spotify Technology SA" },
  { symbol: "DASH", name: "DoorDash Inc." },
  { symbol: "TTD", name: "The Trade Desk Inc." },
  { symbol: "PINS", name: "Pinterest Inc." },
  { symbol: "TWLO", name: "Twilio Inc." },
  { symbol: "OKTA", name: "Okta Inc." },
  { symbol: "TEAM", name: "Atlassian Corp." },
  { symbol: "WDAY", name: "Workday Inc." },
  { symbol: "NOW", name: "ServiceNow Inc." },
  { symbol: "VEEV", name: "Veeva Systems Inc." },
  { symbol: "HUBS", name: "HubSpot Inc." },
  { symbol: "MNDY", name: "Monday.com Ltd." },
  { symbol: "ZM", name: "Zoom Video Communications" },
  { symbol: "DOCU", name: "DocuSign Inc." },
  { symbol: "BILL", name: "BILL Holdings Inc." },
  { symbol: "AFRM", name: "Affirm Holdings Inc." },
  { symbol: "UPST", name: "Upstart Holdings Inc." },
  { symbol: "CELH", name: "Celsius Holdings Inc." },
  { symbol: "DKNG", name: "DraftKings Inc." },
  { symbol: "PENN", name: "PENN Entertainment Inc." },
  { symbol: "CHWY", name: "Chewy Inc." },
  { symbol: "ETSY", name: "Etsy Inc." },
  { symbol: "W", name: "Wayfair Inc." },
  { symbol: "CVNA", name: "Carvana Co." },
  { symbol: "GME", name: "GameStop Corp." },
  { symbol: "AMC", name: "AMC Entertainment Holdings" },
  { symbol: "BBBY", name: "Bed Bath & Beyond Inc." },
  { symbol: "TLRY", name: "Tilray Brands Inc." },
  { symbol: "PLUG", name: "Plug Power Inc." },
  { symbol: "FSLR", name: "First Solar Inc." },
  { symbol: "ENPH", name: "Enphase Energy Inc." },
  { symbol: "SEDG", name: "SolarEdge Technologies Inc." },
  { symbol: "RUN", name: "Sunrun Inc." },
];
